<?php

namespace App\Services\WhatsApp;

use App\Models\SystemSetting;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use RuntimeException;

class WhatsAppBootstrapService
{
    public function workerDir(): string
    {
        return base_path('whatsapp-service');
    }

    public function workerEnvPath(): string
    {
        return $this->workerDir().'/.env';
    }

    /**
     * Ensure native-platform settings and worker .env exist for local/production use.
     *
     * @return array<string, mixed>
     */
    public function bootstrap(bool $regenerateToken = false): array
    {
        $this->ensureStorageDirs();

        $token = $this->ensureWorkerToken($regenerateToken);
        $workerUrl = $this->defaultWorkerUrl();

        SystemSetting::set('whatsapp_driver', 'native', 'whatsapp', 'text');
        SystemSetting::set('whatsapp_worker_url', $workerUrl, 'whatsapp', 'text');
        SystemSetting::set('whatsapp_bot_api_url', $workerUrl, 'whatsapp', 'text');

        $this->writeWorkerEnv($token);

        return [
            'driver' => 'native',
            'enabled' => app(WhatsAppConfig::class)->isEnabled(),
            'worker_url' => $workerUrl,
            'worker_env_ready' => is_file($this->workerEnvPath()),
            'worker_token_configured' => $token !== '',
            'bot_number' => app(WhatsAppConfig::class)->botNumber(),
        ];
    }

    public function writeWorkerEnv(?string $token = null): string
    {
        $dir = $this->workerDir();
        if (! is_dir($dir)) {
            throw new RuntimeException('WhatsApp worker directory not found: '.$dir);
        }

        $token ??= app(WhatsAppConfig::class)->workerToken();
        if ($token === '') {
            $token = $this->ensureWorkerToken();
        }

        $config = app(WhatsAppConfig::class);
        $port = (int) (parse_url($config->workerUrl(), PHP_URL_PORT) ?: 8765);
        $botNumber = $config->botNumber();

        $lines = [
            '# Auto-generated by APM — php artisan whatsapp:bootstrap',
            'PORT='.$port,
            'WORKER_TOKEN='.$token,
            '',
            '# MySQL (same database as Laravel APM)',
            'DB_HOST='.config('database.connections.mysql.host', '127.0.0.1'),
            'DB_PORT='.config('database.connections.mysql.port', 3306),
            'DB_DATABASE='.config('database.connections.mysql.database', 'apm'),
            'DB_USERNAME='.config('database.connections.mysql.username', 'root'),
            'DB_PASSWORD='.$this->escapeEnvValue((string) config('database.connections.mysql.password', '')),
            '',
            '# Bot owner number — digits only with country code',
            'BOT_NUMBER='.$botNumber,
            '',
            'AUTH_DIR=../storage/whatsapp-auth',
            'BIND_HOST=127.0.0.1',
            'NODE_ENV='.(app()->environment('production') ? 'production' : 'development'),
            '',
        ];

        File::put($this->workerEnvPath(), implode("\n", $lines));
        @chmod($this->workerEnvPath(), 0600);

        return $this->workerEnvPath();
    }

    public function defaultWorkerUrl(): string
    {
        $fromEnv = trim((string) env('WHATSAPP_WORKER_URL', ''));
        if ($fromEnv !== '') {
            return rtrim($fromEnv, '/');
        }

        $port = (int) env('WHATSAPP_WORKER_PORT', 8765);

        return 'http://127.0.0.1:'.$port;
    }

    private function ensureWorkerToken(bool $regenerate = false): string
    {
        $existing = WhatsAppSecretStore::get('whatsapp_worker_token');
        if ($existing !== '' && ! $regenerate) {
            WhatsAppSecretStore::set('whatsapp_worker_token', $existing);

            return $existing;
        }

        $token = Str::random(48);
        WhatsAppSecretStore::set('whatsapp_worker_token', $token);

        return $token;
    }

    private function ensureStorageDirs(): void
    {
        $authDir = storage_path('whatsapp-auth');
        if (! is_dir($authDir)) {
            File::makeDirectory($authDir, 0700, true);
        } else {
            @chmod($authDir, 0700);
        }
    }

    private function escapeEnvValue(string $value): string
    {
        if ($value === '') {
            return '';
        }
        if (preg_match('/[\s#="\']/', $value)) {
            return '"'.str_replace(['\\', '"'], ['\\\\', '\\"'], $value).'"';
        }

        return $value;
    }
}
