<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Activity Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            margin: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h3 {
            color: #07579A;
            margin: 5px 0;
        }
        .header img {
            height: 70px;
            margin-bottom: 10px;
        }
        .info-table, .activities-table, .team-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        .info-table td {
            padding: 5px;
        }
        .info-table td strong {
            color: #07579A;
        }
        .activities-table th, .activities-table td,
        .team-table th, .team-table td {
            border: 1px solid #999;
            padding: 6px;
            text-align: left;
            font-size: 10px;
        }
        .activities-table th, .team-table th {
            background-color: #07579A;
            color: #fff;
        }
        .no-data {
            text-align: center;
            color: #888;
            font-style: italic;
        }
        .stats-section {
            margin-bottom: 20px;
        }
        .stats-grid {
            display: table;
            width: 100%;
            margin-bottom: 15px;
        }
        .stat-item {
            display: table-cell;
            width: 25%;
            text-align: center;
            padding: 10px;
            border: 1px solid #ddd;
            background-color: #f9f9f9;
        }
        .stat-number {
            font-size: 18px;
            font-weight: bold;
            color: #07579A;
        }
        .stat-label {
            font-size: 10px;
            color: #666;
            text-transform: uppercase;
        }
        .section-title {
            color: #07579A;
            font-size: 14px;
            font-weight: bold;
            margin: 15px 0 10px 0;
            border-bottom: 2px solid #07579A;
            padding-bottom: 5px;
        }
        .filter-info {
            background-color: #f0f8ff;
            padding: 10px;
            border-left: 4px solid #07579A;
            margin-bottom: 15px;
        }
        .filter-info strong {
            color: #07579A;
        }
    </style>
</head>
<body>

<div class="header">
    <img src="<?= base_url('assets/images/AU_CDC_Logo-800.png') ?>" alt="AU CDC Logo" style="height:100px;">
    <h3>Activity Management Report</h3>
    <small><?= $division->division_name ?? 'Division Report' ?></small>
</div>

<!-- Report Information -->
<table class="info-table">
    <tr>
        <td><strong>Division:</strong> <?= $division->division_name ?? 'N/A' ?></td>
        <td><strong>Report Date:</strong> <?= date('M d, Y') ?></td>
    </tr>
    <tr>
        <td><strong>Date Range:</strong> <?= $date_range ?? 'All Time' ?></td>
        <td><strong>Generated By:</strong> <?= $this->session->userdata('user')->fname . ' ' . $this->session->userdata('user')->lname ?></td>
    </tr>
</table>

<!-- Filter Information -->
<?php if (!empty($filters['start_date']) || !empty($filters['end_date']) || !empty($filters['team_members']) || !empty($filters['work_plan'])): ?>
<div class="filter-info">
    <strong>Applied Filters:</strong>
    <?php if (!empty($filters['start_date']) || !empty($filters['end_date'])): ?>
        Date Range: <?= $date_range ?><br>
    <?php endif; ?>
    <?php if (!empty($filters['team_members'])): ?>
        Team Members: <?= is_array($filters['team_members']) ? implode(', ', $filters['team_members']) : $filters['team_members'] ?><br>
    <?php endif; ?>
    <?php if (!empty($filters['work_plan'])): ?>
        Work Plan: <?= $filters['work_plan'] ?><br>
    <?php endif; ?>
</div>
<?php endif; ?>

<!-- Statistics Section -->
<?php if (!empty($statistics)): ?>
<div class="section-title">Activity Statistics</div>
<div class="stats-grid">
    <div class="stat-item">
        <div class="stat-number"><?= $statistics['total'] ?? 0 ?></div>
        <div class="stat-label">Total Activities</div>
    </div>
    <div class="stat-item">
        <div class="stat-number"><?= $statistics['completed'] ?? 0 ?></div>
        <div class="stat-label">Completed</div>
    </div>
    <div class="stat-item">
        <div class="stat-number"><?= $statistics['pending'] ?? 0 ?></div>
        <div class="stat-label">In Progress</div>
    </div>
    <div class="stat-item">
        <div class="stat-number"><?= $statistics['overdue'] ?? 0 ?></div>
        <div class="stat-label">Overdue</div>
    </div>
</div>
<?php endif; ?>

<!-- Team Performance Section -->
<?php if (!empty($team_performance)): ?>
<div class="section-title">Team Performance Summary</div>
<table class="team-table">
    <thead>
        <tr>
            <th>#</th>
            <th>Team Member</th>
            <th>Job Title</th>
            <th>Total Activities</th>
            <th>Completed</th>
            <th>Pending</th>
            <th>Completion Rate</th>
        </tr>
    </thead>
    <tbody>
        <?php if (!empty($team_performance)): $i = 1; foreach ($team_performance as $member): ?>
            <?php 
            $completion_rate = ($member->total_activities > 0) ? 
                round(($member->completed_activities / $member->total_activities) * 100) : 0;
            ?>
            <tr>
                <td><?= $i++ ?></td>
                <td><?= $member->fname . ' ' . $member->lname ?></td>
                <td><?= $member->job_name ?? 'N/A' ?></td>
                <td><?= $member->total_activities ?? 0 ?></td>
                <td><?= $member->completed_activities ?? 0 ?></td>
                <td><?= $member->pending_activities ?? 0 ?></td>
                <td><?= $completion_rate ?>%</td>
            </tr>
        <?php endforeach; else: ?>
            <tr>
                <td colspan="7" class="no-data">No team performance data available</td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>
<?php endif; ?>

<!-- Activities Section -->
<div class="section-title">Activity Details</div>
<table class="activities-table">
    <thead>
        <tr>
            <th>#</th>
            <th>Activity Name</th>
            <th>Team Member</th>
            <th>Division</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Status</th>
            <th>Report</th>
        </tr>
    </thead>
    <tbody>
        <?php if (!empty($activities)): $i = 1; foreach ($activities as $activity): ?>
            <tr>
                <td><?= $i++ ?></td>
                <td><?= $activity->activity_name ?? 'N/A' ?></td>
                <td><?= $activity->member_name ?? 'N/A' ?></td>
                <td><?= $activity->division_name ?? 'N/A' ?></td>
                <td><?= $activity->start_date ?? 'N/A' ?></td>
                <td><?= $activity->end_date ?? 'N/A' ?></td>
                <td>
                    <?php 
                    $hasReport = !empty($activity->report_id);
                    if ($hasReport) {
                        echo '<span style="color: #28a745; font-weight: bold;">Completed</span>';
                    } else {
                        echo '<span style="color: #ffc107; font-weight: bold;">In Progress</span>';
                    }
                    ?>
                </td>
                <td>
                    <?php if ($hasReport): ?>
                        <span style="color: #28a745;">✓ Submitted</span>
                    <?php else: ?>
                        <span style="color: #6c757d;">Pending</span>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; else: ?>
            <tr>
                <td colspan="8" class="no-data">No activities found for the selected criteria</td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>

</body>
</html>
