/** Keep in sync with Modules/Payroll/app/Support/PayrollPermissions.php */
export const PAYROLL_PERMS = {
  VIEW_HUB: 110,
  MANAGE_SETUP: 111,
  MANAGE_STAFF_PAY: 112,
  RUN_PAYROLL: 113,
  MANAGE_LOANS: 114,
  APPROVE_LOANS: 115,
  REQUEST_LOAN: 116,
  VIEW_OWN_PAYSLIPS: 117,
} as const

export const PAYROLL_MODULE_PERMS = [
  PAYROLL_PERMS.VIEW_HUB,
  PAYROLL_PERMS.MANAGE_SETUP,
  PAYROLL_PERMS.MANAGE_STAFF_PAY,
  PAYROLL_PERMS.RUN_PAYROLL,
  PAYROLL_PERMS.MANAGE_LOANS,
  PAYROLL_PERMS.APPROVE_LOANS,
  PAYROLL_PERMS.REQUEST_LOAN,
  PAYROLL_PERMS.VIEW_OWN_PAYSLIPS,
] as const
