/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentsManagementPanel: typeof import('./src/components/settings/AgentsManagementPanel.vue')['default']
    AiModelsSettingsPanel: typeof import('./src/components/settings/AiModelsSettingsPanel.vue')['default']
    CategoriesManagementPanel: typeof import('./src/components/settings/CategoriesManagementPanel.vue')['default']
    CbpAvatar: typeof import('./src/components/common/CbpAvatar.vue')['default']
    CbpBadgeStrip: typeof import('./src/components/common/CbpBadgeStrip.vue')['default']
    CbpPageFooter: typeof import('./src/components/layout/CbpPageFooter.vue')['default']
    CbpPageHeading: typeof import('./src/components/common/CbpPageHeading.vue')['default']
    CbpPrimaryNav: typeof import('./src/components/layout/CbpPrimaryNav.vue')['default']
    CbpRichTextEditor: typeof import('./src/components/common/CbpRichTextEditor.vue')['default']
    CbpRoutePreloader: typeof import('./src/components/common/CbpRoutePreloader.vue')['default']
    CbpThemeSwitch: typeof import('./src/components/layout/CbpThemeSwitch.vue')['default']
    CbpTopHeader: typeof import('./src/components/layout/CbpTopHeader.vue')['default']
    DirectorySyncCard: typeof import('./src/components/settings/DirectorySyncCard.vue')['default']
    FaqSourcesSettingsPanel: typeof import('./src/components/settings/FaqSourcesSettingsPanel.vue')['default']
    GeneralSettingsPanel: typeof import('./src/components/settings/GeneralSettingsPanel.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeAgentKanban: typeof import('./src/components/home/HomeAgentKanban.vue')['default']
    IntegrationsSettingsPanel: typeof import('./src/components/settings/IntegrationsSettingsPanel.vue')['default']
    JobsSlaManagementPanel: typeof import('./src/components/settings/JobsSlaManagementPanel.vue')['default']
    KbArticleEditModal: typeof import('./src/components/kb/KbArticleEditModal.vue')['default']
    LoggingAuditPanel: typeof import('./src/components/settings/LoggingAuditPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TicketReassignModal: typeof import('./src/components/tickets/TicketReassignModal.vue')['default']
    UApp: typeof import('./src/components/ui/UApp.vue')['default']
    UAvatar: typeof import('./src/components/ui/UAvatar.vue')['default']
    UBadge: typeof import('./src/components/ui/UBadge.vue')['default']
    UButton: typeof import('./src/components/ui/UButton.vue')['default']
    UCard: typeof import('./src/components/ui/UCard.vue')['default']
    UCheckbox: typeof import('./src/components/ui/UCheckbox.vue')['default']
    UColorInput: typeof import('./src/components/ui/UColorInput.vue')['default']
    UForm: typeof import('./src/components/ui/UForm.vue')['default']
    UFormField: typeof import('./src/components/ui/UFormField.vue')['default']
    UInput: typeof import('./src/components/ui/UInput.vue')['default']
    UModal: typeof import('./src/components/ui/UModal.vue')['default']
    USelect: typeof import('./src/components/ui/USelect.vue')['default']
    USelectMenu: typeof import('./src/components/ui/USelectMenu.vue')['default']
    USwitch: typeof import('./src/components/ui/USwitch.vue')['default']
    UTextarea: typeof import('./src/components/ui/UTextarea.vue')['default']
  }
}
