<?php

namespace App\Console\Commands;

use App\Support\WeeklyBriefingMailTemplate;
use Carbon\Carbon;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Log;

class WeeklyBriefingTestNotificationsCommand extends Command
{
    protected $signature = 'weekly-briefing:test-notifications {email? : Recipient address (default: andrewa@africacdc.org)}';

    protected $description = 'Send sample Weekly brief emails (deadline-style reminder + compiled-style notice) to verify mail delivery.';

    public function handle(): int
    {
        $email = (string) ($this->argument('email') ?: 'andrewa@africacdc.org');
        $email = trim($email);
        if (! filter_var($email, FILTER_VALIDATE_EMAIL)) {
            $this->error('Invalid email address: '.$email);

            return self::FAILURE;
        }

        $y = Carbon::now()->isoWeekYear();
        $w = Carbon::now()->isoWeek();
        $appUrl = htmlspecialchars(rtrim((string) config('app.url'), '/'), ENT_QUOTES, 'UTF-8');
        $indexUrl = htmlspecialchars(route('weekly-briefing.index', [], true), ENT_QUOTES, 'UTF-8');

        $reminderInner = <<<HTML
<p><strong>TEST</strong> — This sample was generated by <code>weekly-briefing:test-notifications</code>.</p>
<p>Production contributor reminders use the same Africa CDC layout, personalised salutation, <strong>submission deadline</strong>, and links to <strong>start</strong> or <strong>open the draft</strong>, plus the <a href="{$indexUrl}">Weekly brief</a> module in APM.</p>
<p>Example production subject: <em>Weekly brief reminder — [reporting unit]</em> · ISO week W{$w} / {$y}</p>
<p><a href="{$appUrl}">APM home</a></p>
HTML;
        $reminderHtml = WeeklyBriefingMailTemplate::wrap(null, 'Weekly brief (test)', $reminderInner);

        $subjectPrefix = env('MAIL_SUBJECT_PREFIX', 'APM').': ';
        $reminderSubject = $subjectPrefix.'[TEST] Weekly brief reminder — W'.$w.'/'.$y.WeeklyBriefingMailTemplate::subjectSuffix();

        try {
            if (! sendEmail($email, $reminderSubject, $reminderHtml)) {
                Log::warning('weekly-briefing:test-notifications reminder sendEmail returned false', ['to' => $email]);
                $this->error('Reminder test mail failed (Exchange / mail transport returned false).');

                return self::FAILURE;
            }
        } catch (\Throwable $e) {
            Log::warning('weekly-briefing:test-notifications reminder mail failed', ['e' => $e->getMessage(), 'to' => $email]);
            $this->error('Reminder test mail failed: '.$e->getMessage());

            return self::FAILURE;
        }

        $compiledInner = <<<HTML
<p><strong>TEST</strong> — This sample was generated by <code>weekly-briefing:test-notifications</code> from the APM Jobs page or Artisan.</p>
<p>In production, the compiled <strong>Weekly brief</strong> email is sent at <strong>summary_send_time</strong> on the configured weekday to <strong>compiled report recipients</strong> and includes the organisation-wide compiled PDF and full completion summary (when configured).</p>
<p>When enabled in settings, division heads of department receive their division’s PDF copy; division directors receive a separate <strong>director report</strong> (division submissions only) and a scoped completion summary.</p>
<p>Current ISO week: <strong>W{$w} / {$y}</strong></p>
<p><a href="{$appUrl}">{$appUrl}</a></p>
HTML;
        $compiledHtml = WeeklyBriefingMailTemplate::wrap(null, 'Weekly brief (test — compiled style)', $compiledInner);

        $compiledSubject = $subjectPrefix.'[TEST] Weekly brief compiled — W'.$w.'/'.$y.WeeklyBriefingMailTemplate::subjectSuffix();

        try {
            if (! sendEmail($email, $compiledSubject, $compiledHtml)) {
                Log::warning('weekly-briefing:test-notifications compiled sendEmail returned false', ['to' => $email]);
                $this->error('Compiled test mail failed (Exchange / mail transport returned false).');

                return self::FAILURE;
            }
        } catch (\Throwable $e) {
            Log::warning('weekly-briefing:test-notifications compiled mail failed', ['e' => $e->getMessage(), 'to' => $email]);
            $this->error('Compiled test mail failed: '.$e->getMessage());

            return self::FAILURE;
        }

        $this->info("Sent 2 test messages to {$email} (reminder-style + compiled-style).");

        return self::SUCCESS;
    }
}
