#!/bin/bash
set -e

STAFF_DB="${STAFF_DB_NAME:-staff}"
APM_DB="${APM_DB_NAME:-apm_local}"

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
CREATE DATABASE IF NOT EXISTS \`${STAFF_DB}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS \`${APM_DB}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON \`${STAFF_DB}\`.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON \`${APM_DB}\`.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
EOSQL
